# ----------------------------------
# Site attributes
# ----------------------------------
title:            Shashank Sharma
description:      "Shashank Sharma Backend - Web Developer Nodejs,Python"

author:
  name:           Shashank Sharma
  description:    Backend Developer
  url:            https://shashank34.github.io/
  email:          shashanks835@gmail.com
  twitter:        https://twitter.com/shashankupadh13
  github:         https://github.com/shashank34
  facebook:       https://www.facebook.com/shashanks835
  linkedin:       https://www.linkedin.com/in/shashank-sharma-ssh
  avatar:         https://en.gravatar.com/userimage/188044257/62967d251689545aa833ffff0af23d57.jpg?size=150

footer_text:     'Shaking the snow globe'

# ----------------------------------
# Site settings
# ----------------------------------
baseurl:          ""
blog_url:         "/blog"
url:              "https://shashank34.github.io"
locale:           en
disqus_enable:    true
disqus_shortname: shashankssh
# gems:      [jekyll-paginate]

#ga_tracker_id:    5189486-5 # ==> blog.adrianorosa.com

encoding:         UTF-8
timezone:         Asia/Kolkata




# ----------------------------------
# Build settings
# ----------------------------------
markdown:         kramdown
# markdown_ext:     "markdown,mkdown,mkdn,mkd,md"
keep_files:       [".git", ".svn", ".png", ".js", ".css", ".jpeg"]

kramdown:
  input:          GFM
  # auto_ids:       true
  # footnote_nr:    1
  # entity_output:  as_char
  # toc_levels:     1..6
  # smart_quotes:   lsquo,rsquo,ldquo,rdquo
  # enable_coderay: false



highlighter:      pygments
lsi:              true

# ----------------------------------
# Path settings
# ----------------------------------
plugins_dir:      _source/_plugins
source:           _source
destination:      _site
# layouts_dir:      _source/_layouts
# data_dir:         _source/_data
exclude:          [resources, template, .xml, .php, WXR]
permalink:        none
paginate:         7
paginate_path:    'blog/page/:num'
# include:          ['_pages']


excerpt_separator: "\n\n"

defaults:
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: post
      author: Shashank Sharma
      comments: open # enable disqus by default to all posts
  -
    scope:
      path: "blog"
      type: "page"
    values:
      layout: base
      category: blog
      dsq_count: true
  -
    scope:
      path: "blog/category"
      type: "page"
    values:
      layout: post_category
      category: blog
      dsq_count: true

# safe:        false
host:        127.0.0.1
port:        4000
